### ISSUE TITLE
feat: system service discovery should get ride of route-rule

### ISSUE THREAD

**Issue by andrewshan** [polarismesh/polaris-cpp#2]
**What is the feature you want to add?**
sdk discover polaris.discover, polaris.healthcheck, polaris.monitor, should not rely on route-rule

**Why do you want to add this feature?**
user install standalone version, he won't add the routerule to service

**How to implement this feature?**
use metadata routing instead of rulebase routing

**Additional context**

**Comment by wssgyyg** [comment]
polaris-cpp already user metadata routing to discover inner service.
https://github.com/polarismesh/polaris-cpp/blob/main/polaris/context.cpp#L374

**Comment by wssgyyg** [comment]
polaris-cpp already user metadata routing to discover inner service.
https://github.com/polarismesh/polaris-cpp/blob/main/polaris/context.cpp#L374
